name: Test

on:
  pull_request:
    types: [labeled]
    
env:
  FIREBASE_ONE: 11111
  FIREBASE_TWO: 22222

jobs:
  the-test:
    if: github.event.label.name == 'one' || github.event.label.name == 'two'
    runs-on: ubuntu-latest
    # set name to the label name
    name: the-${{ github.event.label.name }}-test
    steps:
      - name: set one 
        if: github.event.label.name == 'one'
        run: |
          echo "THE_VAR=${{ env.FIREBASE_ONE }}" >> GITHUB_ENV
      - name: set two
        if: github.event.label.name == 'two'
        run: |
          echo "THE_VAR=${{ env.FIREBASE_TWO }}" >> GITHUB_ENV
      
      - run: echo $GITHUB_ENV
      - run: env
      - run: echo $THE_VAR
      - run: echo ${{ env.THE_VAR }}
    
      
